
CREATE TABLE ARTISTS(
    art_id serial PRIMARY KEY,
    name varchar(60) UNIQUE NOT NULL,
    Genre varchar(30) UNIQUE NOT NULL
);
CREATE TABLE USERs(
    user_id serial PRIMARY KEY,
    username VARCHAR (50) UNIQUE NOT NULL,
    password VARCHAR (100) UNIQUE NOT NULL,
    type VARCHAR(20) NOT NULL
);
CREATE TABLE CONCERT
(
    con_id int PRIMARY KEY NOT NULL,
    con_name VARCHAR(50) UNIQUE NOT NULL,
    con_info VARCHAR(100)
);
CREATE TABLE CON_ARTS
(
    ca_id INT PRIMARY KEY NOT NULL,
    con_id INTEGER NOT NULL REFERENCES CONCERT(con_id) ON DELETE CASCADE ON UPDATE CASCADE,
    art_id INTEGER NOT NULL REFERENCES ARTISTS(art_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TICKETS
(
    tid INTEGER PRIMARY KEY NOT NULL,
    price DECIMAL(5,2) NOT NULL,
    con_id INTEGER NOT NULL REFERENCES CONCERT(con_id) ON DELETE CASCADE ON UPDATE CASCADE,
    user_ud INTEGER NOT NULL REFERENCES USERs(user_id) ON DELETE CASCADE ON UPDATE CASCADE

);
ALTER TABLE CONCERT
ADD COLUMN date_time TIMESTAMP UNIQUE NOT NULL;
ALTER TABLE CONCERT
ADD COLUMN ticket_no INTEGER;

ALTER TABLE TICKETS
ADD COLUMN buyer_name VARCHAR(60) NOT NULL;


